### ISSUE TITLE
I cant submitted 

### ISSUE THREAD

**Issue by rayhuang05** [rayhuang05/retina-images#1]
@charlie-quinn

**Comment by rayhuang05** [comment]
I completed the assignment, but when I drag it into morbot, I cant submit it.

**Comment by charlie-quinn** [comment]
Mark has been manually updated! 🤖✅

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by rayhuang05** [comment]
Hi, it’s Ray, I’m sorry, I was gonna go in today for class, but I’ve had
fever, and I’m extremely sick, may I go in other time? Like maybe tmr
night?
